---
title: Standard de reproductibilité, un principe important en recherche.   

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Laura Béland
    affiliation: a

address:
  - code: a
    address: Université de Sherbrooke, Départment de biologie, 2500 Boulevard de l'Université, Sherbrooke, Québec, J1K 2R1

abstract: |
  

keywords:
  - reproductibilité
  - transparence
  - protocole
  - méthode

## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle.sty

bibliography: pnas-sample.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

#output: rticles::pnas_article
---

# Introduction

Depuis la pandémie, la quantité d'article scientifique publié sur des sites de pré-publication à énormément augmenté. Cette accès facile à la publication sans délais important et sans révisions par les paires est intéressante pour les chercheurs qui veulent faire connaître leurs recherches et cherchant la reconnaissance dans leur domaine. Cepandant, un article publié dans de tel site n'est pas révisé et peut contenir plusieurs erreurs qui, normalement, aurait pu être détecté avec la publication par des réviseur. Ainsi, la reproductibilité des résultats obtenu dans ses articles peut être difficile.

Le but de cette essaie est de permettre aux chercheurs de comprendre l'importance des principes de standards de reproduction, en mettrant de l'avant les avantages et les inconvéniants de la transparence, ainsi que quelques méthodes pour y parvenir.

# mise en contexte

Il est primordial de comprendre l'importance de la reproductibilité dans un contexte scientifique. Normalement, un journal scientifique va effectuer une révision d'un article reçue pour, ainsi, minimiser les erreurs potentielles. Cependant, même après une révision, la reproductibilité des expérimentations scientifiques est quelque chose de difficile à atteindre. La majorité des chercheurs, soit près de 70%, affirment n'ayant pas réussi à reproduire l'expérience d'un autre chercheur selon l'article de @baker2016reproducibility. Étant donné la grande augmentation de rapport de recherche mis à la disposition du publique sur les sites de pré-publication, la reproductibilité est de plus en importante. Elle permet de s'assurer un minimum d'erreur dans les données d'une analyse, ainsi que d'assurer la fiabilité des résultats obtenus et que l'analyse est juste. Comme les résultats des articles pré-publiés pourraient faire l'objet d'intérêt et pourraient être utilisé par d'autre chercheur cherchant à pousser plus loins l'analyse ou vérifier les résultats obtenus, il faut émettre le doute que les résultats de ces articles ne sont peut-être pas fiables. Ce sont des articles qui n'ont pas été révisé. Si l'on voit les site de pré-publication comme des sites permettant de vérifier la reproductibilité des analyses et pour mettre le doigt sur des erreurs possibles pourraient être une bonne chose. Ainsi ces articles pourraient être poffinée et pourraient par la suite être considéré pour la créatoin de d'autres recherches ou analyses. Il faut par contre, s'assurer que l'article à tout ce qu'il faut pour être reproduites par des paires.

Pour permettre une meilleure reproductibilité, il y a plusieurs choses a prendre en considération. Tout d'abord, il y la méthode de prise de données. Dans l'article


Un autre aspect qui vient jouer un rôle au niveau de la reproductibilité et qui est très important dans plusieurs aspect dans un article de recherche est la transparence. Un sujet où se ne sont pas tout les chercheurs qui sont du même avis.

# Conclusion

Ainsi, les standards de reproductibilité sont imoportants pour un article scientifique. Ils permettent de confirmer les résultats et les analyses présent dans l'articles. Pour s'assurer d'une bonne reproductibilité, il faut avoir des bonnes pratiques au niveau de la prise de données, de l'entreposage de données et de leurs utilisation avec les différent outils d'analyse. Il est également important de faire de la transparence, dans une certaine mesure, pour permettre à d'autres chercheur de pouvoir répliquer la recherche. Même si la science est un domaine en contant développement, si nous ne mettons pas les mesures nécéssaires pour permettre une bonne reproductibilité, il sera difficile d'avancé vers de nouvelles découvertes. 

\newpage

# Bibliographie {.unnumbered}
